### ISSUE TITLE
libdoc on multible resources files does not work as expected

### ISSUE THREAD

**Issue by sues003** [qualersoft/robotframework-gradle-plugin#58]
When executing libdoc on a folder containing multiple *.resource files I'll get an error about unknown extension 'resource' because the extension is taken from the source file.
Therefor I wanted to use the `--format` switch but have to recognize that it is not exposed by the configuration.
As a workaround I looped over all *.resource-files in that folder an created a dedicated libdoc task. This works well when executing the single tasks. But, to not always have to run each of them one by one, I've created a simple task which depends on all of them, but that also hasn't worked. Because, in this case, libdoc-config-property will be configured only once and shared between all tasks.

Desired behavior:
1. make format an exposed property (maybe default to HTML)
2. if working on a root directory task should iterate over all files and configure the single execution approriatly
3. not quite sure if this is possible but it would be greate if multible resource-docs would be combined in one output file.

**Comment by mathze** [comment]
In response to:
1. make format an exposed property was done, but no default to allow compatibility with pre 4.0 RF version. Maybe later if pre 4.0 support will be droped.
2. Done
3. Unfortunately libdoc does not provide such a functionality maybe we should try to create a feature request in rf-project.
